// Copyright 2025 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-graphics -i leftcut.png -f rgb565`

#pragma once

#include <qp.h>

extern const uint32_t gfx_leftcut_length;
extern const uint8_t  gfx_leftcut[146467];
